### list

GET  http://localhost:9229/list?app=app1&env=dev&ns=public

### update
POST http://localhost:9229/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "cs.a": "dev0000000014",
  "cs.c": "cc2005",
  "cs.b": "dd200225"
}


### version
GET http://localhost:9229/version?app=app1&env=dev&ns=public

### demo 8081
GET http://localhost:8081/demo